// <auto-generated />
using System;
using Amiasea.Enterprise.Data.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amiasea.Enterprise.Data.Migration.Core.Migrations;

[DbContext(typeof(CoreDbContext))]
partial class CoreDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20261008150046_InitialCreate";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("core")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Amiasea.Enterprise.Data.Core.Entity.Cart", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.ToTable("Carts", "core");
            });

        modelBuilder.Entity("Amiasea.Enterprise.Data.Core.Entity.CartItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CartId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CartId");

                b.HasIndex("ProductId");

                b.ToTable("CartItems", "core");
            });

        modelBuilder.Entity("Amiasea.Enterprise.Data.Core.Entity.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Products", "core");
            });

        modelBuilder.Entity("Amiasea.Enterprise.Data.Core.Entity.CartItem", b =>
            {
                b.HasOne("Amiasea.Enterprise.Data.Core.Entity.Cart", null)
                    .WithMany("Items")
                    .HasForeignKey("CartId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Amiasea.Enterprise.Data.Core.Entity.Product", null)
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Amiasea.Enterprise.Data.Core.Entity.Cart", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
    }
}
